---
# the v0 API also references paths from within this file

x-original-swagger-version: "2.0"
openapi: "3.0.1"
info:
  title: "Issue n"
  version: "0.0.1"
  description: |
     Demonstration of formparam bug.
paths:
  /createToken:
    post:
      summary: |
         Create a token from username and password
      operationId: "createToken"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        "200":
          description: "authentication response"
          content:
            application/json:
              schema:
                type: "string"

